### ISSUE TITLE
让我进hack.chat

### ISSUE THREAD

**Issue by singer01** [zzChumo/zzChat#1]
我因为反对中修的教育制度，被里面一群走资派封禁了

**Comment by zzChumo** [comment]
建议先了解一下什么是Issue、Issue有什么用，以及如何正确的提出一个Issue。
https://yinguobing.com/submit-issue-the-right-way/

---
_只要您的态度和提问方式有过于离谱的问题，我们就会拒绝为您解决该条Issue。_
